### ISSUE TITLE
server url

### ISSUE THREAD

**Issue by vallla-git** [luckyking113/Almacenes#1]
what's the api url to server?
what's api directory in backend project?

**Comment by luckyking113** [comment]
https://secuencia.studio:2083/cpsess3898129854/frontend/paper_lantern/index.html?login=1&post_login=48504319825569

secuamuz / lu9XSAA8ZMWu

**Comment by vallla-git** [comment]
what's the directory name in backend code for api?

**Comment by luckyking113** [comment]
you can find the backend api in there.
I guess, the backend api folder name is "backendapi" .

**Comment by valla-git** [comment]
really ugly url

**Comment by vallla-git** [comment]
where did you get it?

**Comment by vallla-git** [comment]
tested with postman but didn't work

**Comment by valla-git** [comment]
solved
